name: id77
on:
  schedule:
    - cron: '1 16 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: id77
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: id77
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/id77/QuantumultX.git"
          source_branch: "master"
          destination_branch: "id77"
          github_token: ${{ secrets.PAT }}
