name: langkhach270389
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: langkhach270389
jobs:
  repo-sync: 
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: langkhach270389
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/langkhach270389/Quantumult-X-LK.git"
          source_branch: "rm"
          destination_branch: "langkhach270389"
          github_token: ${{ secrets.PAT }}
